//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kitapSatis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kitaplar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kitaplar()
        {
            this.siparis = new HashSet<siparis>();
        }
    
        public int kitapId { get; set; }
        public string kitapAdi { get; set; }
        public decimal kitapFiyat { get; set; }
        public int kitapSayfasi { get; set; }
        public int kitapYayineviId { get; set; }
        public int kitapBasim { get; set; }
        public string kitapResmi { get; set; }
        public int kitapKategoriId { get; set; }
    
        public virtual kategori kategori { get; set; }
        public virtual yayinevi yayinevi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siparis> siparis { get; set; }
    }
}
