//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kitapSatis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siparis
    {
        public int siparisId { get; set; }
        public int siparisMusteriId { get; set; }
        public int siparisKodu { get; set; }
        public int siparisKitapId { get; set; }
        public string siparisTarihi { get; set; }
    
        public virtual kitaplar kitaplar { get; set; }
        public virtual musteri musteri { get; set; }
    }
}
